[build]
command = "npm run build -w demos/middleware"
publish = "demos/middleware/.next"
ignore = "if [ $CACHED_COMMIT_REF == $COMMIT_REF ]; then (exit 1); else git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ./; fi;"

[build.environment]
NEXT_SPLIT_API_ROUTES = "true"
NEXT_BUNDLE_BASED_ON_NFT_FILES = "true"

[[plugins]]
package = "@netlify/plugin-nextjs"

# This is a fake plugin, that makes it run npm install
[[plugins]]
package = "@netlify/plugin-local-install-core"

[[plugins]]
package = "./demos/plugin-wrapper"
# Uncomment this if testing the built files rather than dev
# [dev]
# framework = "#static"
# [[redirects]]
# from = "/_next/static/*"
# to = "/static/:splat"
# status = 200
# [[redirects]]
# from = "/*"
# to = "/.netlify/functions/___netlify-handler"
# status = 200
