name: Run e2e (default demo)
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
    paths:
      - 'demos/default/**/*.{js,jsx,ts,tsx}'
      - 'cypress/e2e/default/**/*.{ts,js}'
      - 'src/**/*.{ts,js}'

jobs:
  cypress:
    name: Cypress
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Github token
        uses: navikt/github-app-token-generator@v1
        id: get-token
        with:
          private-key: ${{ secrets.TOKENS_PRIVATE_KEY }}
          app-id: ${{ secrets.TOKENS_APP_ID }}

      - name: Checkout @netlify/wait-for-deploy-action
        uses: actions/checkout@v3
        with:
          repository: netlify/wait-for-deploy-action
          token: ${{ steps.get-token.outputs.token }}
          path: ./.github/actions/wait-for-netlify-deploy

      - name: Wait for Netlify Deploy
        id: deploy
        uses: ./.github/actions/wait-for-netlify-deploy
        with:
          site-name: netlify-plugin-nextjs-demo
          timeout: 300

      - name: Deploy successful
        if: ${{ steps.deploy.outputs.origin-url }}
        run: echo ${{ steps.deploy.outputs.origin-url }}

      - name: Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - run: npm install

      - name: Cypress run
        if: ${{ steps.deploy.outputs.origin-url }}
        id: cypress
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          record: true
          parallel: true
          config-file: cypress/config/ci.config.ts
          group: 'Next Runtime - Demo'
          spec: cypress/e2e/default/*
        env:
          DEBUG: '@cypress/github-action'
          CYPRESS_baseUrl: ${{ steps.deploy.outputs.origin-url }}
          CYPRESS_NETLIFY_CONTEXT: ${{ steps.deploy.outputs.context }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_RECORD_KEY: ${{ secrets.DEFAULT_CYPRESS_RECORD_KEY }}
